mode_topic: "fsm_node/mode" #Topic name for the FSM state
source_topics: #Mapping from cmd source name to topics
  lane: "lane_controller_node/cmd"
  intersection: "open_loop_intersection_control_node/cmd"
  coordination: "veh_coordinator_node/cmd"
mappings: #Mapping from FSMStates.state to cmd source names. Allows different FSM mode to map to same source.
  LANE_FOLLOWING: "lane"
  INTERSECTION_CONTROL: "intersection"
  COORDINATION: "coordination"